theme: jekyll-theme-midnight
title: Nowoczesne Delphi VCL
description: Informacje o nowoczesnym podejściu do pisania aplikacji VCL
show_downloads: false
# logo: [Location of the logo]
# google_analytics: [Your Google Analytics tracking ID]
