theme: jekyll-theme-minimal
title: The title of your site
description: A short description of your site's purpose
show_downloads: true
# logo: [Location of the logo]
# google_analytics: [Your Google Analytics tracking ID]
